### ISSUE TITLE
WMAgents failing to inject large blocks (500 files) into DBS 

### ISSUE THREAD

**Issue by amaltaro** [dmwm/dbs2go#48]
This issue is very similar to what has been reported in this WMCore ticket:
https://github.com/dmwm/WMCore/issues/11170

however, since it happened to a block created today, I decided to use a different thread to discuss this, which likely has a different root cause.

Here is what I see in the DBS3Upload log for vocms0282, where it prepared this block to be injected into DBS today:
```
2022-06-10 01:59:53,264:140249312470784:INFO:DBSUploadPoller:Queueing block for insertion: /TKCosmics_0T_13p6TeV/Run3Winter22CosmicDR-0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#ef4c86cc-7cbc-4005-959c-e0bf0e68ae65
```

and then we received a `Gateway Time-out` error [1], exactly 5min after the request was made (thus, CMSWEB frontend timeout).

After the failure above, the component tries to insert that same block again in the next cycle:
```
2022-06-10 02:10:46,236:140249312470784:INFO:DBSUploadPoller:Queueing block for insertion: /TKCosmics_0T_13p6TeV/Run3Winter22CosmicDR-0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#ef4c86cc-7cbc-4005-959c-e0bf0e68ae65
```

which now fails with a `Error: concurrency error`, which we are more familiar with but it was supposed to have been fixed since May 31st AFAICT. Error details are in [2].

@vkuznet can you please check the server logs and try to understand why we keep having issues with this `insertFilesViaChunks` API? I have two hypothesis here:
a) either we are still failing to rollback the whole transaction, in case there is an issue with one of the sub-set insertions; or
b) the error message is now different and we no longer receive a `Block BLAH already exists` in the error message, and we are unable to detect blocks+files that have been successfully inserted already.
 
[1]
```
2022-06-10 02:04:53,988:140249312470784:ERROR:DBSUploadPoller:Error trying to process block /TKCosmics_0T_13p6TeV/Run3Winter22CosmicDR-0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#ef4c86cc-7cbc-4005-959c-e0bf0e68ae65 through DBS. Error: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
Traceback (most recent call last):
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/py3-dbs3-client/4.0.7/lib/python3.8/site-packages/dbs/apis/dbsClient.py", line 445, in __callServer
    self.http_response = method_func(self.url, method, params, data, request_headers)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/py3-dbs3-pycurl/3.17.7-comp/lib/python3.8/site-packages/RestClient/RestApi.py", line 42, in post
    return http_request(self._curl)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/py3-dbs3-pycurl/3.17.7-comp/lib/python3.8/site-packages/RestClient/RequestHandling/HTTPRequest.py", line 62, in __call__
    raise HTTPError(effective_url, http_code, http_response.msg, http_response.raw_header, http_response.body)
RestClient.ErrorHandling.RestClientExceptions.HTTPError: HTTP Error 504: Gateway Time-out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/wmagentpy3/2.0.2.patch1/lib/python3.8/site-packages/WMComponent/DBS3Buffer/DBSUploadPoller.py", line 92, in uploadWorker
    dbsApi.insertBulkBlock(blockDump=block)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/py3-dbs3-client/4.0.7/lib/python3.8/site-packages/dbs/apis/dbsClient.py", line 606, in insertBulkBlock
    result =  self.__callServer("bulkblocks", data=blockDump, callmethod='POST' )
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/py3-dbs3-client/4.0.7/lib/python3.8/site-packages/dbs/apis/dbsClient.py", line 457, in __callServer
    self.__parseForException(data)
  File "/data/srv/wmagent/v2.0.2.patch1/sw/slc7_amd64_gcc630/cms/py3-dbs3-client/4.0.7/lib/python3.8/site-packages/dbs/apis/dbsClient.py", line 483, in __parseForException
    raise http_error
RestClient.ErrorHandling.RestClientExceptions.HTTPError: HTTP Error 504: 
URL=https://cmsweb-prod.cern.ch:8443/dbs/prod/global/DBSWriter/bulkblocks
Code=504
Message=Gateway Time-out
Header=HTTP/1.1 100 Continue

HTTP/1.1 504 Gateway Time-out
Date: Fri, 10 Jun 2022 00:04:53 GMT
Server: Apache
Content-Type: text/html
Content-Length: 160
CMS-Server-Time: D=300180998 t=1654819193805190
```

[2]
```
2022-06-10 02:10:46,478:140249312470784:INFO:DBSUploadPoller:About to call insert block for: /TKCosmics_0T_13p6TeV/Run3Winter22CosmicDR-0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#ef4c86cc-7cbc-4005-959c-e0bf0e68ae65
2022-06-10 02:10:47,229:140249312470784:ERROR:DBSUploadPoller:Error trying to process block /TKCosmics_0T_13p6TeV/Run3Winter22CosmicDR-0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#674398f4-0cce-416f-82bf-c18a90023062 through DBS. Error: [{"error":{"reason":"DBSError Code:110 Description:DBS DB insert record error Function:dbs.bulkblocks.insertFilesViaChunks Message: Error: concurrency error","message":"0847832ee70dbdfd68453ecf1a79cdf8f208c937ac40eec7c8bcb569c10a3fbb unable to insert files, error DBSError Code:110 Description:DBS DB insert record error Function:dbs.bulkblocks.insertFilesViaChunks Message: Error: concurrency error","function":"dbs.bulkblocks.InsertBulkBlocksConcurrently","code":110},"http":{"method":"POST","code":400,"timestamp":"2022-06-10 00:10:47.2219685 +0000 UTC m=+730069.050618884","path":"/dbs/prod/global/DBSWriter/bulkblocks","user_agent":"DBSClient/Unknown/","x_forwarded_host":"dbs-prod.cern.ch","x_forwarded_for":"137.138.62.154","remote_addr":"137.138.63.204:46568"},"exception":400,"type":"HTTPError","message":"DBSError Code:110 Description:DBS DB insert record error Function:dbs.bulkblocks.InsertBulkBlocksConcurrently Message:0847832ee70dbdfd68453ecf1a79cdf8f208c937ac40eec7c8bcb569c10a3fbb unable to insert files, error DBSError Code:110 Description:DBS DB insert record error Function:dbs.bulkblocks.insertFilesViaChunks Message: Error: concurrency error Error: nested DBSError Code:110 Description:DBS DB insert record error Function:dbs.bulkblocks.insertFilesViaChunks Message: Error: concurrency error"}]
```

**Comment by vkuznet** [comment]
@amaltaro , here is what I found from DBS logs:
- there are different failures associated with block you provided, e.g. I put pod name and corresponding error message (I cut it off for one particular LFN):
```
/cephfs/product/dbs-logs/dbs2go-global-w-547775c578-kcf75.log-20220610
[2022-06-10 00:27:23.305706095 +0000 UTC m=+731052.017391194] 
bulkblocks2.go:998: ### trec unable to insert File record for lfn
/store/mc/Run3Winter22CosmicDR/TKCosmics_0T_13p6TeV/GEN-SIM-RECO/0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/2820000/47a23496-371c-4565-8755-faaf5025a4f0.root, 
error DBSError Code:110 Description:DBS DB insert record error Function:dbs.files.Insert Message: 
Error: ORA-00001: unique constraint (CMS_DBS3_PROD_GLOBAL_OWNER.TUC_FL_LOGICAL_FILE_NAME) violated

# different dbs writer pod
/cephfs/product/dbs-logs/dbs2go-global-w-547775c578-pxx8l.log-20220610

[2022-06-10 00:10:47.220785932 +0000 UTC m=+730069.049436295]
bulkblocks2.go:998: ### trec unable to insert File record for lfn 
/store/mc/Run3Winter22CosmicDR/TKCosmics_0T_13p6TeV/GEN-SIM-RECO/0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/2820000/47a23496-371c-4565-8755-faaf5025a4f0.root, 
error DBSError Code:110 Description:DBS DB insert record error Function:dbs.files.Insert Message: 
Error: ORA-00001: unique constraint (CMS_DBS3_PROD_GLOBAL_OWNER.TUC_FL_LOGICAL_FILE_NAME) violated
```

The interesting part is this
- your log message reports that it fails for block `/TKCosmics_0T_13p6TeV/Run3Winter22CosmicDR-0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#ef4c86cc-7cbc-4005-959c-e0bf0e68ae65`
- but according to DBS (I queried via dasgoclient), the LFN `/store/mc/Run3Winter22CosmicDR/TKCosmics_0T_13p6TeV/GEN-SIM-RECO/0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/2820000/47a23496-371c-4565-8755-faaf5025a4f0.root` resides in block `/TKCosmics_0T_13p6TeV/Run3Winter22CosmicDR-0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#674398f4-0cce-416f-82bf-c18a90023062`
- therefore it can't be inserted second time, which is what we see from ORACLE errors above.

My question is what is JSON payload the WMAgent tries to inject? Can you posted somewhere that we can see where this LFN belongs? There are other LFNs but at least this one provides errors in different DBS pods and we can concentrate on this one to debug the issue.

**Comment by vkuznet** [comment]
I also checked that both blocks: `/TKCosmics_0T_13p6TeV/Run3Winter22CosmicDR-0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#ef4c86cc-7cbc-4005-959c-e0bf0e68ae65` and `/TKCosmics_0T_13p6TeV/Run3Winter22CosmicDR-0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#674398f4-0cce-416f-82bf-c18a90023062` have file, run, lumis in DBS. Therefore, this issue is different from https://github.com/dmwm/WMCore/issues/11170

**Comment by amaltaro** [comment]
Valentin, there is a total of 4 TKCosmics_0T_13p6TeV blocks failing currently:
```
/TKCosmics_38T_13p6TeV/Run3Winter22CosmicDR-123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#36cae9b9-809e-4f11-9641-d146e86eb103
/TKCosmics_38T_13p6TeV/Run3Winter22CosmicDR-123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#b7d274e5-d850-49e5-a4ff-47c059ab2495
/TKCosmics_0T_13p6TeV/Run3Winter22CosmicDR-0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#ef4c86cc-7cbc-4005-959c-e0bf0e68ae65
/TKCosmics_0T_13p6TeV/Run3Winter22CosmicDR-0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#674398f4-0cce-416f-82bf-c18a90023062
```

**Comment by vkuznet** [comment]
You still did not provide initial JSON payload, please do.

Let's concentrate on two blocks `674398f4-0cce-416f-82bf-c18a90023062` and `ef4c86cc-7cbc-4005-959c-e0bf0e68ae65` which are already in DBS and they have LFNs (and FILE_LUMIS). Why WMA re-injecting them? I would assume that if they were injected (since now they are present in DBS) there is no need to re-inject them.

**Comment by vkuznet** [comment]
Here is the first one:
```
./dasgoclient -query="block=$blk" -json | jq
[
  {
    "block": [
      {
        "block.name": null,
        "block.size": null,
        "block_id": 27395457,
        "create_by": "WMAgent",
        "created_by": "WMAgent",
        "creation_date": 1654788535,
        "creation_time": 1654788535,
        "dataset": "/TKCosmics_0T_13p6TeV/Run3Winter22CosmicDR-0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO",
        "dataset_id": 14385828,
        "file_count": 500,
        "last_modification_date": 1654788535,
        "last_modified_by": "WMAgent",
        "modification_time": 1654788535,
        "modified_by": "WMAgent",
        "name": "/TKCosmics_0T_13p6TeV/Run3Winter22CosmicDR-0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#ef4c86cc-7cbc-4005-959c-e0bf0e68ae65",
        "nfiles": 500,
        "open_for_writing": 0,
        "origin_site_name": "T1_US_FNAL_Disk",
        "size": 2067208864468
      }
    ],
    "das": {
      "expire": 1654887129,
      "instance": "prod/global",
      "primary_key": "block.name",
      "record": 1,
      "services": [
        "dbs3:blocks"
      ]
    },
    "qhash": "eaf81226a2ec4d8efcd94c30616091b7"
  }
]
```
and here is another one:
```
./dasgoclient -query="block=$blk2" -json | jq
[
  {
    "block": [
      {
        "block.name": null,
        "block.size": null,
        "block_id": 27395418,
        "create_by": "WMAgent",
        "created_by": "WMAgent",
        "creation_date": 1654787143,
        "creation_time": 1654787143,
        "dataset": "/TKCosmics_0T_13p6TeV/Run3Winter22CosmicDR-0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO",
        "dataset_id": 14385828,
        "file_count": 500,
        "last_modification_date": 1654787143,
        "last_modified_by": "WMAgent",
        "modification_time": 1654787143,
        "modified_by": "WMAgent",
        "name": "/TKCosmics_0T_13p6TeV/Run3Winter22CosmicDR-0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#674398f4-0cce-416f-82bf-c18a90023062",
        "nfiles": 500,
        "open_for_writing": 0,
        "origin_site_name": "T2_CH_CERN",
        "size": 2078946379139
      }
    ],
    "das": {
      "expire": 1654887157,
      "instance": "prod/global",
      "primary_key": "block.name",
      "record": 1,
      "services": [
        "dbs3:blocks"
      ]
    },
    "qhash": "1ff5913b79317e8d31ea4aa962f34974"
  }
]
```

**Comment by vkuznet** [comment]
the suspicious part is that both claims to have 500 LFNs which is what the limit for single chunk is in DBS server. You also posted that initially it was a time out on FE after 5 minutes which I wonder played the role in the error. I need to see initial payload and check LFNs in these blocks. Then I can look-up if there are missing LFNs which may caused by timeout.

**Comment by amaltaro** [comment]
> You still did not provide initial JSON payload, please do.

I haven't provided a JSON yet because we don't make a JSON dump for every block that the component inserts into DBS. In order to get it, we need to adapt the code to dump it for that specific block.
I changed the code, but there are 100s of blocks to be loaded by the agent and it might take a while to produce that block dump. I will update it here once I have it. And here it is:
https://amaltaro.web.cern.ch/amaltaro/forWMCore/Issue_11170/674398f4-0cce-416f-82bf-c18a90023062.json

> Why WMA re-injecting them? I would assume that if they were injected (since now they are present in DBS) there is no need to re-inject them.

Because the component didn't get a successful HTTP response (200/201) back from the server, so in the agent database that block and its files are still marked as not-inserted. What used to happen in the Python-based server was that, the next cycle we try to inject a block that is already in the DBS server - including ALL its relevant information - we would simply get an error message saying `Block BLAH already exists`, which we acknowledge and then mark the block/files as injected in the agent database.

**Comment by vkuznet** [comment]
ok, two more things to check:
- can you check agent database for those 4 blocks and tell me how many lfns they had?
- it seems to me we have different behavior in DBS Py vs GO servers. The py server returns error with block name which you use, while Go fails to inject provided block and does not provide you such message. We can resolve it in two different way:
-- either I add check to Go server to check first if block exists and return error message, but for that I need to know the syntax of error message and actual HTTP code to return, or
-- you add to WMA code a call to DBS server to check if block exist and based on this call you either inject or not the block.

The reason I don't like server to return block error message since I have no idea what are the conditions if block exists with all its content or not. We had to use open blocks, and therefore block may exist but may not have files in it. Do we still have such conditions? In other words, what is a definition of block existence in DBS?

**Comment by amaltaro** [comment]
> can you check agent database for those 4 blocks and tell me how many lfns they had?

All of them have 500 files!
```
2022-06-10 19:23:31,270:140462623237888:INFO:DBSUploadPoller:Have 500 files for block /TKCosmics_0T_13p6TeV/Run3Winter22CosmicDR-0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#ef4c86cc-7cbc-4005-959c-e0bf0e68ae65
2022-06-10 20:58:56,387:139731998406400:INFO:DBSUploadPoller:Have 500 files for block /TKCosmics_0T_13p6TeV/Run3Winter22CosmicDR-0T_123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#674398f4-0cce-416f-82bf-c18a90023062

2022-06-10 12:57:06,118:140499005875968:INFO:DBSUploadPoller:Have 500 files for block /TKCosmics_38T_13p6TeV/Run3Winter22CosmicDR-123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#36cae9b9-809e-4f11-9641-d146e86eb103
2022-06-10 12:57:13,331:140499005875968:INFO:DBSUploadPoller:Have 500 files for block /TKCosmics_38T_13p6TeV/Run3Winter22CosmicDR-123X_mcRun3_2021cosmics_design_deco_v1-v2/GEN-SIM-RECO#b7d274e5-d850-49e5-a4ff-47c059ab2495
```

> it seems to me we have different behavior in DBS Py vs GO servers. The py server returns error with block name which you use, while Go fails to inject provided block and does not provide you such message.

it's what I mentioned in my very first post to this issue.

> either I add check to Go server to check first if block exists and return error message, but for that I need to know the syntax of error message and actual HTTP code to return, or

This is my preference! It's cheaper, since it's all done on the server side and it requires no changes to the clients (well, in this case only WMAgent and CRAB). It looks like we do not rely on any special HTTP status code, but only on the error message:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/DBS3Buffer/DBSUploadPoller.py#L96

but since you started working on standardizing error codes, you might already consider a specific http status code for this. It's up to you. 

> The reason I don't like server to return block error message since I have no idea what are the conditions if block exists with all its content or not. For example, we had to use open blocks, and therefore block may exist but may not have files in it.

Yes and no! There is no concept of "open" blocks in DBS3. It was one of the major changes - and benefits - on top of DBS2. We should assume that, IF there is a block in DBS Server, then it has complete information. It was not the case in the past weeks because there was a bug with the migration to the Go-based server. But my comment remains, if a block is in DBS, then we should not worry whether it has all the information or not.

**Comment by vkuznet** [comment]
@amaltaro , I made necessary changes and tested locally the insertion of the same payload (the same block name). The error message is the following:
```
[{"error":{"reason":"Block /NoBPTX/fernance-private-CosmicSkim-Run2018Dv2-8884fb883da6c66a605f7e93ffab3213/USER#f11be9dd-8fcf-4089-a880-7f57ee39bd63 already exists","message":"Data already exist in DBS","function":"dbs.bulkblocks.InsertBulkBlocksConcurrently","code":101},"http":{"method":"POST","code":400,"timestamp":"2022-06-11 10:13:14.458492 -0400 EDT m=+5.655915560","path":"/dbs2go/bulkblocks","user_agent":"curl/7.83.1","x_forwarded_host":"","x_forwarded_for":"","remote_addr":"127.0.0.1:60270"},"exception":400,"type":"HTTPError","message":"DBSError Code:101 Description:DBS DB error Function:dbs.bulkblocks.InsertBulkBlocksConcurrently Message:Data already exist in DBS Error: Block /NoBPTX/fernance-private-CosmicSkim-Run2018Dv2-8884fb883da6c66a605f7e93ffab3213/USER#f11be9dd-8fcf-4089-a880-7f57ee39bd63 already exists"}]
```
Please note few things:
- The HTTP error code remains the same, it is 400 Bad Request, and I doubt we need to change it. 
- The internal DBS server error code I used is code 101 Database error

The changes now in testebed and I request that you try to inject the same data twice, i.e. you'll need to call `bulkblocks` API with the same payload, and see if it works with the message you requested.

**Comment by amaltaro** [comment]
Thanks Valentin. I am testing it soon.

**Comment by amaltaro** [comment]
@vkuznet thanks for providing this fix. It seems to be working properly. I marked a block and its files as not-injected in my testbed agent, and this is the result in the logs:
```
2022-06-13 15:22:22,571:140055964497728:INFO:DBSUploadPoller:About to call insert block for: /RelValDarkSUSY_14TeV/Integ_Test-SC_LHE_Ext_Agent204_Val_Alanv11-v11/GEN-SIM#13d33641-c28d-4702-8d3a-98fc6226881f
2022-06-13 15:22:22,706:140055964497728:WARNING:DBSUploadPoller:Block /RelValDarkSUSY_14TeV/Integ_Test-SC_LHE_Ext_Agent204_Val_Alanv11-v11/GEN-SIM#13d33641-c28d-4702-8d3a-98fc6226881f already exists. Marking it as uploaded.
```

> Please note few things:
>    The HTTP error code remains the same, it is 400 Bad Request, and I doubt we need to change it.
>    The internal DBS server error code I used is code 101 Database error

Noted!

From my side, this fix can go in in production whenever it's convenient to you.

**Comment by vkuznet** [comment]
I deployed the patch to production, closing this issue.

**Comment by amaltaro** [comment]
Thanks Valentin. I see that those 4 blocks have now been marked as injected in the agents.
